openapi: 3.0.0
info:
  title: NotCoin Telegram Mini App API
  version: 1.0.0
  description: Base API URL is your stack url which should be equal to {VITE_API_ENDPOINT}
paths:
  /gameEssentials/listDailyBoosters:
    post:
      summary: List daily boosters
      tags:
        - Boosters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: A list of daily boosters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyBoosterItem'
        '401':
          description: Unauthorized
  /gameEssentials/listBoosters:
    post:
      summary: List boosters
      tags:
        - Boosters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: A list of boosters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoosterItem'
        '401':
          description: Unauthorized
  /gameEssentials/upgradeBooster:
    post:
      summary: Upgrade a booster
      tags:
        - Boosters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Upgraded booster
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoosterItem'
        '401':
          description: Unauthorized
  /gameEssentials/getGameContext:
    post:
      summary: Get game context
      tags:
        - Games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Game context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGameContext'
        '401':
          description: Unauthorized
  /gameEssentials/syncGameContext:
    post:
      summary: Sync game context
      tags:
        - Games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pointsBalance:
                  type: integer
                energyBalance:
                  type: integer
      responses:
        '200':
          description: Synced game context
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGameContext'
        '401':
          description: Unauthorized
  /referrals/listReferrals:
    post:
      summary: List referrals
      tags:
        - Referrals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: A list of referrals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReferredUser'
        '401':
          description: Unauthorized
  /rewardableTasks/listTasks:
    post:
      summary: List tasks
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
  /rewardableTasks/checkTask:
    post:
      summary: Check task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
                telegramInitData:
                  type: string
      responses:
        '200':
          description: Checked task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '412':
          description: Precondition Failed
  /twaAuth/signIn:
    post:
      summary: Sign in
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                telegramInitData:
                  type: string
      responses:
        '200':
          description: Signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '401':
          description: Unauthorized
components:
  schemas:
    DailyBoosterItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        maxAmount:
          type: integer
        remainingAmount:
          type: integer
    BoosterItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        type:
          type: string
        currentPrice:
          type: number
        currentLevel:
          type: number
    UserGameContext:
      type: object
      properties:
        levelName:
          type: string
        energyLimit:
          type: integer
        remainingEnergyRefills:
          type: integer
        totalEarnedPoints:
          type: integer
        energyBalance:
          type: integer
        pointBalance:
          type: integer
        multitapLevel:
          type: integer
        energyLimitLevel:
          type: integer
        lastEnergyRefilledAt:
          type: string
          format: date-time
        lastEnergyUpdatedAt:
          type: string
          format: date-time
        lastPointUpdatedAt:
          type: string
          format: date-time
        maxEnergyRefillsPerDay:
          type: integer
        pointEarnsPerClick:
          type: integer
        energyConsumesPerClick:
          type: integer
        energyRefillInterval:
          type: integer
    ReferredUser:
      type: object
      properties:
        referredUserId:
          type: string
        referredUserName:
          type: string
        referredJoinedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        reward:
          type: integer
        type:
          type: string
        actionName:
          type: string
        link:
          type: string
        imageType:
          type: string
        completed:
          type: boolean
        timeToWait:
          type: integer
        numWaitSeconds:
          type: string
          format: date-time
    Session:
      type: object
      properties:
        id:
          type: integer
        authUserId:
          type: string
        telegramId:
          type: integer
        telegramUsername:
          type: string
        tonWalletAddress:
          type: string
        isPremium:
          type: boolean
        accessToken:
          type: string
          
